name: Release

on:
  push:
    tags: ['*']

jobs:
  prebuilds:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            arch: x64
          - os: macos-latest
            arch: x64
          - os: windows-latest
            arch: x86
          - os: windows-latest
            arch: x64
    runs-on: ${{ matrix.os }}
    name: Build ${{ matrix.os }} ${{ matrix.arch }}
    env:
      NODE_VERSION: 16
      VERSION_NAME: ${{ github.ref_name }}-${{ matrix.os }}-${{ matrix.arch }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Set up node ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v2
        with:
          registry-url: 'https://registry.npmjs.org'
          node-version: ${{ env.NODE_VERSION }}
          architecture: ${{ matrix.arch }}
      - name: Install dependencies
        shell: bash
        run: npm install --build-from-source
      - name: Prebuild ${{ env.VERSION_NAME }}
        shell: bash
        run: npm run prebuild --v8_enable_pointer_compression=false --v8_enable_31bit_smis_on_64bit_arch=false
      - name: Create artifact
        shell: bash
        run: |
          tar -zcvf $ARCHIVE_NAME -C prebuilds .
          stat "$ARCHIVE_NAME"
        env:
          ARCHIVE_NAME: ${{ env.VERSION_NAME }}.tar.gz
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.VERSION_NAME }}
          path: ${{ env.VERSION_NAME }}.tar.gz
          retention-days: 1

  release_and_publish:
    runs-on: ubuntu-latest
    needs: prebuilds
    permissions:
      contents: write
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Set up node ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v2
        with:
          registry-url: 'https://registry.npmjs.org'
      - run: npm install --build-from-source
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          path: prebuilds
      - name: Create ${{ github.ref }} release
        uses: softprops/action-gh-release@v1
        with:
          files: prebuilds/*/*.tar.gz
        env:
          ARCHIVE_NAME: ${{ github.ref_name }}-${{ runner.os }}-${{ runner.arch }}.tar
      - run: npm publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
