#!/usr/bin/env bash
#
## Proxy packer command for different OSes

EXTPATH="$(cd "$(dirname "${BASH_SOURCE[0]}")"; pwd -P)"

case $(echo `uname -sm` | sed 's/ /-/g') in
  'Linux-86_64')
    ${EXTPATH}/packer-0.12.1-linux-amd64 "$@"; exit $?
    ;;
  'Linux-loongarch64')
    ${EXTPATH}/packer-1.6.6-linux-loongarch64 "$@"; exit $?
    ;;
  'Darwin-x86_64')
    ${EXTPATH}/packer-0.12.1-darwin-amd64 "$@"; exit $?
    ;;
  \?)
    echo 'OS Not Supported'; exit 1
    ;;
esac
